Add documentation

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,19 +25,14 @@ jobs:
         with:
           python-version: '3.11'
 
-      - name: Install Dependencies
+      - name: Install Pytest
         run: |
           pip install pytest
 
       - name: Run Tests
         id: test
         run: |
-          pytest --junitxml=report.xml || echo "TEST_FAILED=true" >> $GITHUB_ENV
-
-      - name: Check if report.xml is generated
-        run: |
-          ls -la
-          cat report.xml  
+          pytest --junitxml=report.xml || echo "TEST_FAILED=true" >> $GITHUB_ENV 
     
       - name: Analyze Failures with Ollama
         if: env.TEST_FAILED == 'true'
